version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
gyro = true
farmersdelight = true
createendertransmission = true
burnt = true
createbigcannons = true
tfmg = true
drivebywire = true
s_a_b = true
createpropulsion = true
create = true
pantographsandwires = true
createrailwaysnavigator = true
aeronautics = true
create_aeronautics_toolgun = true
simulated = true
cbc_compact_mount = true
copycats = true
minecraft = true
dndecor = true
create_connected = true
createdeco = true
powergrid = true
railways = true
sliceanddice = true
dragonlib = true
create_bb = true
tracks = true
create_tweaked_controllers = true
exposure = true
